### PR TITLE
Fix Sign out link

### LINKED ISSUE #190: Sign Out link not actually logging the User out
### Descriptive summary
As reported by Kacy, and confirmed, it appears that the sign out functionality is not working.

Initial suspicion is that because the entire application requires authentication, the redirect after the signout causes an immediate signin again.

We should either figure out a way to force a true SSO signout, or redirect the user to the LiSN homepage, or something.

### PR DESCRIPTION
**Pull request by VivianChu**
Fixes #190 

#### Local Checklist
- [x] Tests written and passing locally?
- [x] Code style checked?
- [x] QA-ed locally?
- [x] Rebased with `master` branch?
- [ ] Configuration updated (if needed)?
- [ ] Documentation updated (if needed)?

#### What does this PR do?
Fix Sign out function by creating and redirecting to a public logout page.

#### Screenshots

---
logout

@ucsdlib/developers - please review

### CODE REVIEW

File: app/controllers/sessions_controller.rb [hunk 1]
```diff
@@ -40,8 +40,8 @@ def destroy
     destroy_user_session
 
     # rubocop:disable Metrics/LineLength
-    redirect_to root_url,
-                notice: 'You have been logged out of this applicaton. To logout of all Single Sign-On applications, close your browser'
+    redirect_to logout_url,
+                notice: 'You have been logged out of this application. To logout of all Single Sign-On applications, close your browser'
```
Comment (mcritchlow) [inline app/controllers/sessions_controller.rb]: should we change `application` to `High Five!`? Otherwise this looks great to me.
