### PR TITLE
initial helm chart

### LINKED ISSUE #301: Create initial Helm chart for High Five
### Descriptive summary

Create initial Helm chart for deploying the High Five application to a k8s cluster.

### Rationale
see: #297 

### Expected behavior
- A `/.hifive` chart should be created with Helm and populated to support necessary secrets, ingress, and database support
- Use official postgres Helm chart as dependency
- Create a `k3d` script for local testing of the chart
- PVC for postgres database
- PVC for postfix spoolfile
- ...

see: recent Starlight and Theodor work for reference implementations

### LINKED ISSUE #332: Figure out why precompiling assets fails in Dockerfile
### Descriptive summary

When working on #318 I noticed that while there was no "error" generated, the pre-compiled assets did not successfully persist in the built container image.

Temporarily, this has been moved to the entrypoint script, but this is less ideal since it has to be run each time the app is deployed, therefore slowing deployment down.

### PR DESCRIPTION
**Pull request by mcritchlow**
Fixes #301 
Fixes #332 

#### Local Checklist
- [ ] Tests written and passing locally?
- [ ] Code style checked?
- [x] QA-ed locally?
- [x] Rebased with `master` branch?
- [ ] Configuration updated (if needed)?
- [ ] Documentation updated (if needed)?

#### What does this PR do?
- Adds an initial helm chart for High Five
- Adds a dependency on the postgresql helm chart
- Adds a custom email container/service for sending app email via smtp
- Adds a custom Rancher questions.yaml file to ease deployment in
  Rancher
- Adds a custom networking policy which **only** allows the application pod to talk w/ the email pod
- Removes postfix from the Dockerfile since we're using a dedicated container/service for that now

##### Why are we doing this? Any context of related work?
References #301 

Note: The image being used in the helm chart is in docker hub, which i build and pushed manually using `docker build -t ucsdlib/hifive:stable --target production .` AFTER commenting out the shibboleth setting in the production configuration file so that I could test the helm chart w/ developer authentication. Once we have google authentication working via #300 we can test that in Rancher as well.

#### Where should a reviewer start?
You can see this working now in Rancher: https://lib-rancher-lb.ucsd.edu/p/c-28www:p-879gn/apps

I'm going to create a separate ticket to make the `k3d` script work since it's useful but not directly a dependency on the context of this branch/PR

~~I'm also going to create a ticket to look into why the assets precompilation step needed to be moved to the entrypoint script.~~

#### Screenshots
see #301 for some screenshots on the application working, in particular the `kubectl` testing for the networking policy

@ucsdlib/developers - please review

### CODE REVIEW

File: config/application.rb [hunk 1]
```diff
@@ -42,6 +42,10 @@ class Application < Rails::Application
     config.action_mailer.delivery_method = ENV.fetch('APPS_H5_DELIVERY_METHOD').to_sym
     config.action_mailer.default_url_options = { host: ENV.fetch('APPS_H5_EMAIL_HOST') }
 
+    if ENV['APPS_H5_EMAIL_SMTP_HOST'].present? && ENV['APPS_H5_EMAIL_SMTP_PORT'].present?
```
Comment (VivianChu) [inline config/application.rb]: @mcritchlow - Is ENV['APPS_H5_EMAIL_SMTP_HOST'] different than ENV APPS_H5_EMAIL_HOST=localhost:3000 ?

Comment (mcritchlow) [reply config/application.rb]: Ah good question. Yes, and the names are getting confusing. We may want to rename..

`APPS_H5_EMAIL_SMTP_HOST` - this is the postfix email server/host that we need to connect to to send email. In the past, or on current applications, we haven't set this because we've always had postfix installed on the local VM the app is running on. So Rails defaults to `localhost`, which just works. In this case, we actually need to set it the hostname

`APPS_H5_EMAIL_HOST` - this is the base URL that's used when links are generated, and potentially other things for ActionMailer. But this is definitely different than the smtp host

Comment (VivianChu) [reply config/application.rb]: Thanks for the clarification.
